version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /apps/flock-desktop
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      react:
        patterns:
          - react
          - react-dom
          - "@types/react"
          - "@types/react-dom"
  - package-ecosystem: npm
    directory: /services/presence-auth
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
