[package]
name = "flock-pty"
edition.workspace = true
version.workspace = true

[dependencies]
portable-pty = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bytes = { workspace = true }
libc = "0.2"
